# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_npm_node]
steps:
# Install dependencies
- name: node
  id: node-install
  entrypoint: npm
  args: ['install']
  waitFor: ['-']
# Run tests
- name: node
  entrypoint: npm
  args: ['test']
  waitFor: [ node-install ]
# Run custom commands
- name: node
  entrypoint: npm
  args: ['run', 'build']
  waitFor:
    - node-install
- id: Setup Google Project ID
  name: 'ubuntu'
  entrypoint: bash
  env:
    - 'GCLOUD_SERVICE_KEY=${_SERVICE_ACCOUNT}'
    - 'project_name=${PROJECT_ID}'
    - 'GOOGLE_PROJECT_ID=${!project_name}'
  args:
    - -c
    - |
      echo ${PROJECT_ID} &&
      echo GOOGLE_PROJECT_ID
- name: python
  entrypoint: python3
  args: ["-- version"]
- name: 'gcr.io/gcp-runtimes/ubuntu_18_0_4'
  entrypoint: 'curl'
  args: [ 'https://bootstrap.pypa.io/get-pip.py', '-o', 'get-pip.py', '--user' ]
- name: 'gcr.io/gcp-runtimes/ubuntu_18_0_4'
  entrypoint: apt-get
  args: [ 'update', '--allow-releaseinfo-change', 'install', 'python3.7', 'libyaml-dev', 'python3-setuptools', '-y', '--user' ]
- name: python
  entrypoint: python3
  args: [ 'get-pip.py', 'pip==22', '--user']
- name: python
  entrypoint: pip3
  args: ["install", "virtualenv", "--user"]
- name: python
  entrypoint: pip3
  args: ["install", "-r", "requirements.txt", "--user"]
# [END cloudbuild_npm_node]